apiVersion: v1
kind: Service
metadata:
  name: node-oidc-provider-service
spec:
  selector:
    app: node-oidc-provider
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
